import { getPublicSettings, loadArticleRelations, publicArticle, requireDb, safeJson } from './api/v1/_shared.js';

export const deploymentVersion = (env) => String(env?.CF_PAGES_COMMIT_SHA || env?.BUILD_VERSION || '').trim().slice(0,12);
export const bundle = async (env) => ({ db: requireDb(env), settings: await getPublicSettings(requireDb(env)) });
const visibleArticle = `((a.status='published' AND (a.published_at IS NULL OR datetime(a.published_at)<=datetime('now'))) OR (a.status='scheduled' AND a.scheduled_at IS NOT NULL AND datetime(a.scheduled_at)<=datetime('now')))`;
export const articles = async (db) => (await db.prepare(`SELECT a.*,m.public_url AS cover_public_url FROM articles a LEFT JOIN media m ON m.id=a.cover_media_id WHERE ${visibleArticle} AND COALESCE(json_extract(a.metadata_json,'$.isTranslation'),0)=0 ORDER BY COALESCE(a.published_at,a.scheduled_at,a.created_at) DESC LIMIT 300`).all()).results.map(publicArticle);
export const article = async (db,slug) => {const row=await db.prepare(`SELECT a.*,m.public_url AS cover_public_url FROM articles a LEFT JOIN media m ON m.id=a.cover_media_id WHERE a.slug=? AND ${visibleArticle} LIMIT 1`).bind(slug).first();return row?loadArticleRelations(db,publicArticle(row)):null;};
const collection = row => ({id:row.id,type:row.type,title:row.title,theme:row.theme||'',coverUrl:row.cover_public_url||row.cover_url||'',editorNote:row.editor_note||'',year:row.year,volume:row.volume||'',issueNumber:row.issue_number||'',publishedAt:row.published_at||'',metadata:safeJson(row.metadata_json)});
export const collections = async (db) => (await db.prepare(`SELECT c.*,m.public_url AS cover_public_url FROM collections c LEFT JOIN media m ON m.id=c.cover_media_id WHERE c.status='published' AND (c.published_at IS NULL OR datetime(c.published_at)<=datetime('now')) ORDER BY COALESCE(c.published_at,c.created_at) DESC`).all()).results.map(collection);
export const collectionById = async (db,id) => {const row=await db.prepare(`SELECT c.*,m.public_url AS cover_public_url FROM collections c LEFT JOIN media m ON m.id=c.cover_media_id WHERE c.id=? AND c.status='published' AND (c.published_at IS NULL OR datetime(c.published_at)<=datetime('now'))`).bind(id).first();if(!row)return null;const linked=await db.prepare(`SELECT a.*,m.public_url AS cover_public_url FROM collection_articles x JOIN articles a ON a.id=x.article_id LEFT JOIN media m ON m.id=a.cover_media_id WHERE x.collection_id=? AND ${visibleArticle} ORDER BY x.sort_order`).bind(id).all();return{...collection(row),articles:(linked.results||[]).map(publicArticle)};};
const project = row => ({id:row.id,slug:row.slug,type:row.type,title:row.title,summary:row.summary||'',bodyMarkdown:row.body_markdown||'',startDate:row.start_date||'',endDate:row.end_date||'',location:row.location||'',participants:row.participants||'',editor:row.editor||'',coverUrl:row.cover_public_url||row.cover_url||'',metadata:safeJson(row.metadata_json)});
export const projects = async (db) => (await db.prepare(`SELECT p.*,m.public_url AS cover_public_url FROM projects p LEFT JOIN media m ON m.id=p.cover_media_id WHERE p.status='published' ORDER BY COALESCE(p.start_date,p.created_at) DESC`).all()).results.map(project);
export const projectBySlug = async (db,slug) => {const row=await db.prepare(`SELECT p.*,m.public_url AS cover_public_url FROM projects p LEFT JOIN media m ON m.id=p.cover_media_id WHERE p.slug=? AND p.status='published'`).bind(slug).first();if(!row)return null;const relations=await db.prepare(`SELECT relation_type AS relationType,target_id AS targetId,label,sort_order AS sortOrder FROM project_relations WHERE project_id=? ORDER BY sort_order`).bind(row.id).all();return{...project(row),relations:relations.results||[]};};
export const pageBySlug = async (db,slug) => db.prepare(`SELECT id,slug,title,body_markdown AS bodyMarkdown,seo_title AS seoTitle,seo_description AS seoDescription FROM pages WHERE slug=? AND status='published'`).bind(slug).first();
